#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      if !defined(Py_GIL_DISABLED)
#        define Py_LIMITED_API
#      else
#        define Py_LIMITED_API 0x030f0000
#      endif
#    endif

#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      if !defined(Py_GIL_DISABLED)
#        define Py_LIMITED_API
#      else
#        define Py_LIMITED_API 0x030f0000
#      endif
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>
#include <stdlib.h>
#include <string.h>


/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
# define _cffi_float_complex_t   _Fcomplex    /* include <complex.h> for it */
# define _cffi_double_complex_t  _Dcomplex    /* include <complex.h> for it */
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
# define _cffi_float_complex_t   float _Complex
# define _cffi_double_complex_t  double _Complex
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyLong_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyLong_FromLong((long)x) :                                   \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyLong_FromLong((long)x) :                                   \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include "ctd.h"

/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 23), // char *()(char const *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 162), // char const *
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // char const *()(ctd_status)
/*  4 */ _CFFI_OP(_CFFI_OP_ENUM, 1), // ctd_status
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  6 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // char const *()(int)
/*  7 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // char const *()(void)
/* 10 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 11 */ _CFFI_OP(_CFFI_OP_FUNCTION, 33), // ctd_counter *()(int)
/* 12 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 13 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 14 */ _CFFI_OP(_CFFI_OP_FUNCTION, 15), // ctd_point()(ctd_point, ctd_point)
/* 15 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // ctd_point
/* 16 */ _CFFI_OP(_CFFI_OP_NOOP, 15),
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION, 15), // ctd_point()(double, double)
/* 19 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 20 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 21 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 22 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(char *, size_t)
/* 23 */ _CFFI_OP(_CFFI_OP_POINTER, 162), // char *
/* 24 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28), // size_t
/* 25 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(char const *, char *, size_t, size_t *)
/* 27 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 28 */ _CFFI_OP(_CFFI_OP_NOOP, 23),
/* 29 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 30 */ _CFFI_OP(_CFFI_OP_POINTER, 24), // size_t *
/* 31 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 32 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(ctd_counter *, int, int *)
/* 33 */ _CFFI_OP(_CFFI_OP_POINTER, 166), // ctd_counter *
/* 34 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 35 */ _CFFI_OP(_CFFI_OP_POINTER, 7), // int *
/* 36 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 37 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(ctd_counter const *, int *)
/* 38 */ _CFFI_OP(_CFFI_OP_POINTER, 166), // ctd_counter const *
/* 39 */ _CFFI_OP(_CFFI_OP_NOOP, 35),
/* 40 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 41 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(ctd_point *, double, double)
/* 42 */ _CFFI_OP(_CFFI_OP_POINTER, 15), // ctd_point *
/* 43 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 44 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 45 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 46 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(ctd_record *, int32_t, char const *)
/* 47 */ _CFFI_OP(_CFFI_OP_POINTER, 169), // ctd_record *
/* 48 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 21), // int32_t
/* 49 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 50 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 51 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(ctd_value const *, double *)
/* 52 */ _CFFI_OP(_CFFI_OP_POINTER, 171), // ctd_value const *
/* 53 */ _CFFI_OP(_CFFI_OP_POINTER, 19), // double *
/* 54 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 55 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(double, double, double *)
/* 56 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 57 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 58 */ _CFFI_OP(_CFFI_OP_NOOP, 53),
/* 59 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 60 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(int, int, int(*)(int, int, void *), void *, int *)
/* 61 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 62 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 63 */ _CFFI_OP(_CFFI_OP_POINTER, 130), // int(*)(int, int, void *)
/* 64 */ _CFFI_OP(_CFFI_OP_POINTER, 175), // void *
/* 65 */ _CFFI_OP(_CFFI_OP_NOOP, 35),
/* 66 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 67 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(int32_t *)
/* 68 */ _CFFI_OP(_CFFI_OP_POINTER, 48), // int32_t *
/* 69 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 70 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(int32_t *, int32_t *)
/* 71 */ _CFFI_OP(_CFFI_OP_NOOP, 68),
/* 72 */ _CFFI_OP(_CFFI_OP_NOOP, 68),
/* 73 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 74 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(int32_t *, size_t)
/* 75 */ _CFFI_OP(_CFFI_OP_NOOP, 68),
/* 76 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 77 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 78 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(int32_t *, size_t, int32_t)
/* 79 */ _CFFI_OP(_CFFI_OP_NOOP, 68),
/* 80 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 81 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 21),
/* 82 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 83 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(int32_t const *, size_t, ctd_stats *)
/* 84 */ _CFFI_OP(_CFFI_OP_POINTER, 48), // int32_t const *
/* 85 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 86 */ _CFFI_OP(_CFFI_OP_POINTER, 170), // ctd_stats *
/* 87 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 88 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(int32_t const *, size_t, int64_t *)
/* 89 */ _CFFI_OP(_CFFI_OP_NOOP, 84),
/* 90 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 91 */ _CFFI_OP(_CFFI_OP_POINTER, 116), // int64_t *
/* 92 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 93 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(int32_t, size_t, int32_t *, size_t, size_t *)
/* 94 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 21),
/* 95 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 96 */ _CFFI_OP(_CFFI_OP_NOOP, 68),
/* 97 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 98 */ _CFFI_OP(_CFFI_OP_NOOP, 30),
/* 99 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 100 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(uint8_t *, size_t, uint8_t)
/* 101 */ _CFFI_OP(_CFFI_OP_POINTER, 103), // uint8_t *
/* 102 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 103 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 104 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 105 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // ctd_status()(uint8_t const *, size_t, uint8_t *, size_t, size_t *)
/* 106 */ _CFFI_OP(_CFFI_OP_POINTER, 103), // uint8_t const *
/* 107 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 108 */ _CFFI_OP(_CFFI_OP_NOOP, 101),
/* 109 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 110 */ _CFFI_OP(_CFFI_OP_NOOP, 30),
/* 111 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 112 */ _CFFI_OP(_CFFI_OP_FUNCTION, 171), // ctd_value()(double)
/* 113 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 114 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 115 */ _CFFI_OP(_CFFI_OP_FUNCTION, 171), // ctd_value()(int64_t)
/* 116 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 23), // int64_t
/* 117 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 118 */ _CFFI_OP(_CFFI_OP_FUNCTION, 19), // double()(ctd_point const *, ctd_point const *)
/* 119 */ _CFFI_OP(_CFFI_OP_POINTER, 15), // ctd_point const *
/* 120 */ _CFFI_OP(_CFFI_OP_NOOP, 119),
/* 121 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 122 */ _CFFI_OP(_CFFI_OP_FUNCTION, 19), // double()(double, double)
/* 123 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 124 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 125 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 126 */ _CFFI_OP(_CFFI_OP_FUNCTION, 7), // int()(int, int)
/* 127 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 128 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 129 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 130 */ _CFFI_OP(_CFFI_OP_FUNCTION, 7), // int()(int, int, void *)
/* 131 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 132 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 133 */ _CFFI_OP(_CFFI_OP_NOOP, 64),
/* 134 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 135 */ _CFFI_OP(_CFFI_OP_FUNCTION, 7), // int()(void)
/* 136 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 137 */ _CFFI_OP(_CFFI_OP_FUNCTION, 174), // int(*()(int))(int, int)
/* 138 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 139 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 140 */ _CFFI_OP(_CFFI_OP_FUNCTION, 68), // int32_t *()(int32_t, size_t)
/* 141 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 21),
/* 142 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 143 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 144 */ _CFFI_OP(_CFFI_OP_FUNCTION, 48), // int32_t()(int32_t)
/* 145 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 21),
/* 146 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 147 */ _CFFI_OP(_CFFI_OP_FUNCTION, 24), // size_t()(char const *)
/* 148 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 149 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 150 */ _CFFI_OP(_CFFI_OP_FUNCTION, 151), // uint64_t()(uint64_t, uint64_t)
/* 151 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24), // uint64_t
/* 152 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24),
/* 153 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 154 */ _CFFI_OP(_CFFI_OP_FUNCTION, 175), // void()(ctd_counter *)
/* 155 */ _CFFI_OP(_CFFI_OP_NOOP, 33),
/* 156 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 157 */ _CFFI_OP(_CFFI_OP_FUNCTION, 175), // void()(void *)
/* 158 */ _CFFI_OP(_CFFI_OP_NOOP, 64),
/* 159 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 160 */ _CFFI_OP(_CFFI_OP_FUNCTION, 175), // void()(void)
/* 161 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 162 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 163 */ _CFFI_OP(_CFFI_OP_ARRAY, 162), // char[16]
/* 164 */ (_cffi_opcode_t)(16),
/* 165 */ _CFFI_OP(_CFFI_OP_OPEN_ARRAY, 162), // char[]
/* 166 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // ctd_counter
/* 167 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // ctd_number
/* 168 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // ctd_number_kind
/* 169 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // ctd_record
/* 170 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // ctd_stats
/* 171 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // ctd_value
/* 172 */ _CFFI_OP(_CFFI_OP_ARRAY, 19), // double[3]
/* 173 */ (_cffi_opcode_t)(3),
/* 174 */ _CFFI_OP(_CFFI_OP_POINTER, 126), // int(*)(int, int)
/* 175 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_ctd_global_constant(unsigned long long *o)
{
  int n = (ctd_global_constant) <= 0;
  *o = (unsigned long long)((ctd_global_constant) | 0);  /* check that ctd_global_constant is an integer */
  return n;
}

static void _cffi_const_ctd_global_origin(char *o)
{
  *(ctd_point *)o = ctd_global_origin;
}

static int _cffi_const_CTD_NUMBER_I64(unsigned long long *o)
{
  int n = (CTD_NUMBER_I64) <= 0;
  *o = (unsigned long long)((CTD_NUMBER_I64) | 0);  /* check that CTD_NUMBER_I64 is an integer */
  return n;
}

static int _cffi_const_CTD_NUMBER_F64(unsigned long long *o)
{
  int n = (CTD_NUMBER_F64) <= 0;
  *o = (unsigned long long)((CTD_NUMBER_F64) | 0);  /* check that CTD_NUMBER_F64 is an integer */
  return n;
}

static int _cffi_const_CTD_OK(unsigned long long *o)
{
  int n = (CTD_OK) <= 0;
  *o = (unsigned long long)((CTD_OK) | 0);  /* check that CTD_OK is an integer */
  return n;
}

static int _cffi_const_CTD_ERROR_NULL(unsigned long long *o)
{
  int n = (CTD_ERROR_NULL) <= 0;
  *o = (unsigned long long)((CTD_ERROR_NULL) | 0);  /* check that CTD_ERROR_NULL is an integer */
  return n;
}

static int _cffi_const_CTD_ERROR_RANGE(unsigned long long *o)
{
  int n = (CTD_ERROR_RANGE) <= 0;
  *o = (unsigned long long)((CTD_ERROR_RANGE) | 0);  /* check that CTD_ERROR_RANGE is an integer */
  return n;
}

static int _cffi_const_CTD_ERROR_CAPACITY(unsigned long long *o)
{
  int n = (CTD_ERROR_CAPACITY) <= 0;
  *o = (unsigned long long)((CTD_ERROR_CAPACITY) | 0);  /* check that CTD_ERROR_CAPACITY is an integer */
  return n;
}

static int _cffi_const_CTD_ERROR_ALLOCATION(unsigned long long *o)
{
  int n = (CTD_ERROR_ALLOCATION) <= 0;
  *o = (unsigned long long)((CTD_ERROR_ALLOCATION) | 0);  /* check that CTD_ERROR_ALLOCATION is an integer */
  return n;
}

static int _cffi_const_CTD_ERROR_DIVIDE_BY_ZERO(unsigned long long *o)
{
  int n = (CTD_ERROR_DIVIDE_BY_ZERO) <= 0;
  *o = (unsigned long long)((CTD_ERROR_DIVIDE_BY_ZERO) | 0);  /* check that CTD_ERROR_DIVIDE_BY_ZERO is an integer */
  return n;
}

static int _cffi_d_ctd_add(int x0, int x1)
{
  return ctd_add(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_add(PyObject *self, PyObject *args)
{
  int x0;
  int x1;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_add", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_add(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  return pyresult;
}
#else
#  define _cffi_f_ctd_add _cffi_d_ctd_add
#endif

static uint64_t _cffi_d_ctd_add_u64(uint64_t x0, uint64_t x1)
{
  return ctd_add_u64(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_add_u64(PyObject *self, PyObject *args)
{
  uint64_t x0;
  uint64_t x1;
  uint64_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_add_u64", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, uint64_t);
  if (x0 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, uint64_t);
  if (x1 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_add_u64(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, uint64_t);
  return pyresult;
}
#else
#  define _cffi_f_ctd_add_u64 _cffi_d_ctd_add_u64
#endif

static char * _cffi_d_ctd_alloc_greeting(char const * x0)
{
  return ctd_alloc_greeting(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_alloc_greeting(PyObject *self, PyObject *arg0)
{
  char const * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  char * result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_alloc_greeting(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(23));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_alloc_greeting _cffi_d_ctd_alloc_greeting
#endif

static int32_t * _cffi_d_ctd_alloc_sequence_i32(int32_t x0, size_t x1)
{
  return ctd_alloc_sequence_i32(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_alloc_sequence_i32(PyObject *self, PyObject *args)
{
  int32_t x0;
  size_t x1;
  int32_t * result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_alloc_sequence_i32", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int32_t);
  if (x0 == (int32_t)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, size_t);
  if (x1 == (size_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_alloc_sequence_i32(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(68));
  return pyresult;
}
#else
#  define _cffi_f_ctd_alloc_sequence_i32 _cffi_d_ctd_alloc_sequence_i32
#endif

static ctd_status _cffi_d_ctd_apply_callback(int x0, int x1, int(* x2)(int, int, void *), void * x3, int * x4)
{
  return ctd_apply_callback(x0, x1, x2, x3, x4);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_apply_callback(PyObject *self, PyObject *args)
{
  int x0;
  int x1;
  int(* x2)(int, int, void *);
  void * x3;
  int * x4;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;

  if (!PyArg_UnpackTuple(args, "ctd_apply_callback", 5, 5, &arg0, &arg1, &arg2, &arg3, &arg4))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  x2 = (int(*)(int, int, void *))_cffi_to_c_pointer(arg2, _cffi_type(63));
  if (x2 == (int(*)(int, int, void *))NULL && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(64), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (void *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(64), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(35), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (int *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(35), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_apply_callback(x0, x1, x2, x3, x4); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_apply_callback _cffi_d_ctd_apply_callback
#endif

static ctd_status _cffi_d_ctd_ascii_upper(char * x0, size_t x1)
{
  return ctd_ascii_upper(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_ascii_upper(PyObject *self, PyObject *args)
{
  char * x0;
  size_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_ascii_upper", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(23), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (char *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(23), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, size_t);
  if (x1 == (size_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_ascii_upper(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_ascii_upper _cffi_d_ctd_ascii_upper
#endif

static ctd_status _cffi_d_ctd_compute_stats_i32(int32_t const * x0, size_t x1, ctd_stats * x2)
{
  return ctd_compute_stats_i32(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_compute_stats_i32(PyObject *self, PyObject *args)
{
  int32_t const * x0;
  size_t x1;
  ctd_stats * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ctd_compute_stats_i32", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(84), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (int32_t const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(84), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, size_t);
  if (x1 == (size_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(86), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (ctd_stats *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(86), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_compute_stats_i32(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_compute_stats_i32 _cffi_d_ctd_compute_stats_i32
#endif

static ctd_status _cffi_d_ctd_copy_bytes(uint8_t const * x0, size_t x1, uint8_t * x2, size_t x3, size_t * x4)
{
  return ctd_copy_bytes(x0, x1, x2, x3, x4);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_copy_bytes(PyObject *self, PyObject *args)
{
  uint8_t const * x0;
  size_t x1;
  uint8_t * x2;
  size_t x3;
  size_t * x4;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;

  if (!PyArg_UnpackTuple(args, "ctd_copy_bytes", 5, 5, &arg0, &arg1, &arg2, &arg3, &arg4))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(106), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (uint8_t const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(106), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, size_t);
  if (x1 == (size_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(101), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (uint8_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(101), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x3 = _cffi_to_c_int(arg3, size_t);
  if (x3 == (size_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(30), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (size_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(30), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_copy_bytes(x0, x1, x2, x3, x4); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_copy_bytes _cffi_d_ctd_copy_bytes
#endif

static ctd_status _cffi_d_ctd_copy_string(char const * x0, char * x1, size_t x2, size_t * x3)
{
  return ctd_copy_string(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_copy_string(PyObject *self, PyObject *args)
{
  char const * x0;
  char * x1;
  size_t x2;
  size_t * x3;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "ctd_copy_string", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(23), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (char *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(23), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, size_t);
  if (x2 == (size_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(30), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (size_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(30), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_copy_string(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_copy_string _cffi_d_ctd_copy_string
#endif

static ctd_status _cffi_d_ctd_counter_add(ctd_counter * x0, int x1, int * x2)
{
  return ctd_counter_add(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_counter_add(PyObject *self, PyObject *args)
{
  ctd_counter * x0;
  int x1;
  int * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ctd_counter_add", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(33), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (ctd_counter *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(33), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(35), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (int *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(35), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_counter_add(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_counter_add _cffi_d_ctd_counter_add
#endif

static ctd_counter * _cffi_d_ctd_counter_create(int x0)
{
  return ctd_counter_create(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_counter_create(PyObject *self, PyObject *arg0)
{
  int x0;
  ctd_counter * result;
  PyObject *pyresult;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_counter_create(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(33));
  return pyresult;
}
#else
#  define _cffi_f_ctd_counter_create _cffi_d_ctd_counter_create
#endif

static void _cffi_d_ctd_counter_destroy(ctd_counter * x0)
{
  ctd_counter_destroy(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_counter_destroy(PyObject *self, PyObject *arg0)
{
  ctd_counter * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(33), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (ctd_counter *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(33), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { ctd_counter_destroy(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_ctd_counter_destroy _cffi_d_ctd_counter_destroy
#endif

static ctd_status _cffi_d_ctd_counter_get(ctd_counter const * x0, int * x1)
{
  return ctd_counter_get(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_counter_get(PyObject *self, PyObject *args)
{
  ctd_counter const * x0;
  int * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_counter_get", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(38), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (ctd_counter const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(38), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(35), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (int *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(35), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_counter_get(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_counter_get _cffi_d_ctd_counter_get
#endif

static ctd_status _cffi_d_ctd_divide(double x0, double x1, double * x2)
{
  return ctd_divide(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_divide(PyObject *self, PyObject *args)
{
  double x0;
  double x1;
  double * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ctd_divide", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  x0 = (double)_cffi_to_c_double(arg0);
  if (x0 == (double)-1 && PyErr_Occurred())
    return NULL;

  x1 = (double)_cffi_to_c_double(arg1);
  if (x1 == (double)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(53), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(53), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_divide(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_divide _cffi_d_ctd_divide
#endif

static void _cffi_d_ctd_free(void * x0)
{
  ctd_free(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_free(PyObject *self, PyObject *arg0)
{
  void * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(64), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (void *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(64), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { ctd_free(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_ctd_free _cffi_d_ctd_free
#endif

static int(* _cffi_d_ctd_get_binary_operation(int x0))(int, int)
{
  return ctd_get_binary_operation(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_get_binary_operation(PyObject *self, PyObject *arg0)
{
  int x0;
  int(* result)(int, int);
  PyObject *pyresult;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_get_binary_operation(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(174));
  return pyresult;
}
#else
#  define _cffi_f_ctd_get_binary_operation _cffi_d_ctd_get_binary_operation
#endif

static ctd_status _cffi_d_ctd_get_magic(int32_t * x0)
{
  return ctd_get_magic(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_get_magic(PyObject *self, PyObject *arg0)
{
  int32_t * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(68), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_get_magic(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_get_magic _cffi_d_ctd_get_magic
#endif

static int _cffi_d_ctd_global_counter_increment(void)
{
  return ctd_global_counter_increment();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_global_counter_increment(PyObject *self, PyObject *noarg)
{
  int result;
  PyObject *pyresult;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_global_counter_increment(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  return pyresult;
}
#else
#  define _cffi_f_ctd_global_counter_increment _cffi_d_ctd_global_counter_increment
#endif

static void _cffi_d_ctd_global_counter_reset(void)
{
  ctd_global_counter_reset();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_global_counter_reset(PyObject *self, PyObject *noarg)
{

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { ctd_global_counter_reset(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_ctd_global_counter_reset _cffi_d_ctd_global_counter_reset
#endif

static double _cffi_d_ctd_hypot_squared(double x0, double x1)
{
  return ctd_hypot_squared(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_hypot_squared(PyObject *self, PyObject *args)
{
  double x0;
  double x1;
  double result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_hypot_squared", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = (double)_cffi_to_c_double(arg0);
  if (x0 == (double)-1 && PyErr_Occurred())
    return NULL;

  x1 = (double)_cffi_to_c_double(arg1);
  if (x1 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_hypot_squared(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_double(result);
  return pyresult;
}
#else
#  define _cffi_f_ctd_hypot_squared _cffi_d_ctd_hypot_squared
#endif

static ctd_status _cffi_d_ctd_increment(int32_t * x0)
{
  return ctd_increment(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_increment(PyObject *self, PyObject *arg0)
{
  int32_t * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(68), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_increment(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_increment _cffi_d_ctd_increment
#endif

static ctd_status _cffi_d_ctd_make_sequence_i32(int32_t x0, size_t x1, int32_t * x2, size_t x3, size_t * x4)
{
  return ctd_make_sequence_i32(x0, x1, x2, x3, x4);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_make_sequence_i32(PyObject *self, PyObject *args)
{
  int32_t x0;
  size_t x1;
  int32_t * x2;
  size_t x3;
  size_t * x4;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;

  if (!PyArg_UnpackTuple(args, "ctd_make_sequence_i32", 5, 5, &arg0, &arg1, &arg2, &arg3, &arg4))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int32_t);
  if (x0 == (int32_t)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, size_t);
  if (x1 == (size_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(68), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x3 = _cffi_to_c_int(arg3, size_t);
  if (x3 == (size_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(30), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (size_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(30), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_make_sequence_i32(x0, x1, x2, x3, x4); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_make_sequence_i32 _cffi_d_ctd_make_sequence_i32
#endif

static int32_t _cffi_d_ctd_negate_i32(int32_t x0)
{
  return ctd_negate_i32(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_negate_i32(PyObject *self, PyObject *arg0)
{
  int32_t x0;
  int32_t result;
  PyObject *pyresult;

  x0 = _cffi_to_c_int(arg0, int32_t);
  if (x0 == (int32_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_negate_i32(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int32_t);
  return pyresult;
}
#else
#  define _cffi_f_ctd_negate_i32 _cffi_d_ctd_negate_i32
#endif

static int _cffi_d_ctd_operation_add(int x0, int x1)
{
  return ctd_operation_add(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_operation_add(PyObject *self, PyObject *args)
{
  int x0;
  int x1;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_operation_add", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_operation_add(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  return pyresult;
}
#else
#  define _cffi_f_ctd_operation_add _cffi_d_ctd_operation_add
#endif

static int _cffi_d_ctd_operation_multiply(int x0, int x1)
{
  return ctd_operation_multiply(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_operation_multiply(PyObject *self, PyObject *args)
{
  int x0;
  int x1;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_operation_multiply", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_operation_multiply(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  return pyresult;
}
#else
#  define _cffi_f_ctd_operation_multiply _cffi_d_ctd_operation_multiply
#endif

static ctd_point _cffi_d_ctd_point_add(ctd_point x0, ctd_point x1)
{
  return ctd_point_add(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_point_add(PyObject *self, PyObject *args)
{
  ctd_point x0;
  ctd_point x1;
  ctd_point result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_point_add", 2, 2, &arg0, &arg1))
    return NULL;

  if (_cffi_to_c((char *)&x0, _cffi_type(15), arg0) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x1, _cffi_type(15), arg1) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_point_add(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(15));
  return pyresult;
}
#else
static void _cffi_f_ctd_point_add(ctd_point *result, ctd_point *x0, ctd_point *x1)
{
  { *result = ctd_point_add(*x0, *x1); }
}
#endif

static double _cffi_d_ctd_point_dot(ctd_point const * x0, ctd_point const * x1)
{
  return ctd_point_dot(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_point_dot(PyObject *self, PyObject *args)
{
  ctd_point const * x0;
  ctd_point const * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  double result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_point_dot", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(119), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (ctd_point const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(119), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(119), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (ctd_point const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(119), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_point_dot(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_double(result);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_point_dot _cffi_d_ctd_point_dot
#endif

static ctd_point _cffi_d_ctd_point_make(double x0, double x1)
{
  return ctd_point_make(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_point_make(PyObject *self, PyObject *args)
{
  double x0;
  double x1;
  ctd_point result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_point_make", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = (double)_cffi_to_c_double(arg0);
  if (x0 == (double)-1 && PyErr_Occurred())
    return NULL;

  x1 = (double)_cffi_to_c_double(arg1);
  if (x1 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_point_make(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(15));
  return pyresult;
}
#else
static void _cffi_f_ctd_point_make(ctd_point *result, double x0, double x1)
{
  { *result = ctd_point_make(x0, x1); }
}
#endif

static ctd_status _cffi_d_ctd_point_translate(ctd_point * x0, double x1, double x2)
{
  return ctd_point_translate(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_point_translate(PyObject *self, PyObject *args)
{
  ctd_point * x0;
  double x1;
  double x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ctd_point_translate", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(42), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (ctd_point *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(42), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = (double)_cffi_to_c_double(arg1);
  if (x1 == (double)-1 && PyErr_Occurred())
    return NULL;

  x2 = (double)_cffi_to_c_double(arg2);
  if (x2 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_point_translate(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_point_translate _cffi_d_ctd_point_translate
#endif

static ctd_status _cffi_d_ctd_record_initialize(ctd_record * x0, int32_t x1, char const * x2)
{
  return ctd_record_initialize(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_record_initialize(PyObject *self, PyObject *args)
{
  ctd_record * x0;
  int32_t x1;
  char const * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ctd_record_initialize", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(47), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (ctd_record *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(47), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int32_t);
  if (x1 == (int32_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_record_initialize(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_record_initialize _cffi_d_ctd_record_initialize
#endif

static ctd_status _cffi_d_ctd_reverse_i32(int32_t * x0, size_t x1)
{
  return ctd_reverse_i32(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_reverse_i32(PyObject *self, PyObject *args)
{
  int32_t * x0;
  size_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_reverse_i32", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(68), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, size_t);
  if (x1 == (size_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_reverse_i32(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_reverse_i32 _cffi_d_ctd_reverse_i32
#endif

static ctd_status _cffi_d_ctd_scale_i32(int32_t * x0, size_t x1, int32_t x2)
{
  return ctd_scale_i32(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_scale_i32(PyObject *self, PyObject *args)
{
  int32_t * x0;
  size_t x1;
  int32_t x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ctd_scale_i32", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(68), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, size_t);
  if (x1 == (size_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, int32_t);
  if (x2 == (int32_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_scale_i32(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_scale_i32 _cffi_d_ctd_scale_i32
#endif

static char const * _cffi_d_ctd_select_static_string(int x0)
{
  return ctd_select_static_string(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_select_static_string(PyObject *self, PyObject *arg0)
{
  int x0;
  char const * result;
  PyObject *pyresult;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_select_static_string(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(1));
  return pyresult;
}
#else
#  define _cffi_f_ctd_select_static_string _cffi_d_ctd_select_static_string
#endif

static char const * _cffi_d_ctd_status_name(ctd_status x0)
{
  return ctd_status_name(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_status_name(PyObject *self, PyObject *arg0)
{
  ctd_status x0;
  char const * result;
  PyObject *pyresult;

  if (_cffi_to_c((char *)&x0, _cffi_type(4), arg0) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_status_name(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(1));
  return pyresult;
}
#else
#  define _cffi_f_ctd_status_name _cffi_d_ctd_status_name
#endif

static size_t _cffi_d_ctd_string_length(char const * x0)
{
  return ctd_string_length(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_string_length(PyObject *self, PyObject *arg0)
{
  char const * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  size_t result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_string_length(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, size_t);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_string_length _cffi_d_ctd_string_length
#endif

static int _cffi_d_ctd_subtract(int x0, int x1)
{
  return ctd_subtract(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_subtract(PyObject *self, PyObject *args)
{
  int x0;
  int x1;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_subtract", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_subtract(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  return pyresult;
}
#else
#  define _cffi_f_ctd_subtract _cffi_d_ctd_subtract
#endif

static ctd_status _cffi_d_ctd_sum_i32(int32_t const * x0, size_t x1, int64_t * x2)
{
  return ctd_sum_i32(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_sum_i32(PyObject *self, PyObject *args)
{
  int32_t const * x0;
  size_t x1;
  int64_t * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ctd_sum_i32", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(84), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (int32_t const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(84), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, size_t);
  if (x1 == (size_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(91), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (int64_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(91), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_sum_i32(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_sum_i32 _cffi_d_ctd_sum_i32
#endif

static ctd_status _cffi_d_ctd_swap_i32(int32_t * x0, int32_t * x1)
{
  return ctd_swap_i32(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_swap_i32(PyObject *self, PyObject *args)
{
  int32_t * x0;
  int32_t * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_swap_i32", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(68), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(68), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_swap_i32(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_swap_i32 _cffi_d_ctd_swap_i32
#endif

static ctd_status _cffi_d_ctd_value_as_f64(ctd_value const * x0, double * x1)
{
  return ctd_value_as_f64(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_value_as_f64(PyObject *self, PyObject *args)
{
  ctd_value const * x0;
  double * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ctd_value_as_f64", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(52), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (ctd_value const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(52), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(53), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(53), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_value_as_f64(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_value_as_f64 _cffi_d_ctd_value_as_f64
#endif

static ctd_value _cffi_d_ctd_value_from_f64(double x0)
{
  return ctd_value_from_f64(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_value_from_f64(PyObject *self, PyObject *arg0)
{
  double x0;
  ctd_value result;
  PyObject *pyresult;

  x0 = (double)_cffi_to_c_double(arg0);
  if (x0 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_value_from_f64(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(171));
  return pyresult;
}
#else
static void _cffi_f_ctd_value_from_f64(ctd_value *result, double x0)
{
  { *result = ctd_value_from_f64(x0); }
}
#endif

static ctd_value _cffi_d_ctd_value_from_i64(int64_t x0)
{
  return ctd_value_from_i64(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_value_from_i64(PyObject *self, PyObject *arg0)
{
  int64_t x0;
  ctd_value result;
  PyObject *pyresult;

  x0 = _cffi_to_c_int(arg0, int64_t);
  if (x0 == (int64_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_value_from_i64(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_struct((char *)&result, _cffi_type(171));
  return pyresult;
}
#else
static void _cffi_f_ctd_value_from_i64(ctd_value *result, int64_t x0)
{
  { *result = ctd_value_from_i64(x0); }
}
#endif

static char const * _cffi_d_ctd_version(void)
{
  return ctd_version();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_version(PyObject *self, PyObject *noarg)
{
  char const * result;
  PyObject *pyresult;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_version(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(1));
  return pyresult;
}
#else
#  define _cffi_f_ctd_version _cffi_d_ctd_version
#endif

static ctd_status _cffi_d_ctd_xor_bytes(uint8_t * x0, size_t x1, uint8_t x2)
{
  return ctd_xor_bytes(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ctd_xor_bytes(PyObject *self, PyObject *args)
{
  uint8_t * x0;
  size_t x1;
  uint8_t x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  ctd_status result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ctd_xor_bytes", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(101), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (uint8_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(101), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, size_t);
  if (x1 == (size_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint8_t);
  if (x2 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ctd_xor_bytes(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_deref((char *)&result, _cffi_type(4));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ctd_xor_bytes _cffi_d_ctd_xor_bytes
#endif

_CFFI_UNUSED_FN
static void _cffi_checkfld__ctd_point(ctd_point *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { double *tmp = &p->x; (void)tmp; }
  { double *tmp = &p->y; (void)tmp; }
}
struct _cffi_align__ctd_point { char x; ctd_point y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ctd_record(ctd_record *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->id) | 0);  /* check that 'ctd_record.id' is an integer */
  { char(*tmp)[16] = &p->name; (void)tmp; }
  { double(*tmp)[3] = &p->values; (void)tmp; }
}
struct _cffi_align__ctd_record { char x; ctd_record y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ctd_stats(ctd_stats *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->count) | 0);  /* check that 'ctd_stats.count' is an integer */
  (void)((p->minimum) | 0);  /* check that 'ctd_stats.minimum' is an integer */
  (void)((p->maximum) | 0);  /* check that 'ctd_stats.maximum' is an integer */
  (void)((p->sum) | 0);  /* check that 'ctd_stats.sum' is an integer */
  { double *tmp = &p->mean; (void)tmp; }
}
struct _cffi_align__ctd_stats { char x; ctd_stats y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ctd_value(ctd_value *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { ctd_number_kind *tmp = &p->kind; (void)tmp; }
  { ctd_number *tmp = &p->number; (void)tmp; }
}
struct _cffi_align__ctd_value { char x; ctd_value y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ctd_number(ctd_number *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->i64) | 0);  /* check that 'ctd_number.i64' is an integer */
  { double *tmp = &p->f64; (void)tmp; }
}
struct _cffi_align__ctd_number { char x; ctd_number y; };

static int *_cffi_var_ctd_global_counter(void)
{
  return &(ctd_global_counter);
}

static char const *_cffi_var_ctd_global_name(void)
{
  return (ctd_global_name);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "CTD_ERROR_ALLOCATION", (void *)_cffi_const_CTD_ERROR_ALLOCATION, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CTD_ERROR_CAPACITY", (void *)_cffi_const_CTD_ERROR_CAPACITY, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CTD_ERROR_DIVIDE_BY_ZERO", (void *)_cffi_const_CTD_ERROR_DIVIDE_BY_ZERO, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CTD_ERROR_NULL", (void *)_cffi_const_CTD_ERROR_NULL, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CTD_ERROR_RANGE", (void *)_cffi_const_CTD_ERROR_RANGE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CTD_NUMBER_F64", (void *)_cffi_const_CTD_NUMBER_F64, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CTD_NUMBER_I64", (void *)_cffi_const_CTD_NUMBER_I64, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CTD_OK", (void *)_cffi_const_CTD_OK, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ctd_add", (void *)_cffi_f_ctd_add, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 126), (void *)_cffi_d_ctd_add },
  { "ctd_add_u64", (void *)_cffi_f_ctd_add_u64, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 150), (void *)_cffi_d_ctd_add_u64 },
  { "ctd_alloc_greeting", (void *)_cffi_f_ctd_alloc_greeting, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 0), (void *)_cffi_d_ctd_alloc_greeting },
  { "ctd_alloc_sequence_i32", (void *)_cffi_f_ctd_alloc_sequence_i32, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 140), (void *)_cffi_d_ctd_alloc_sequence_i32 },
  { "ctd_apply_callback", (void *)_cffi_f_ctd_apply_callback, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 60), (void *)_cffi_d_ctd_apply_callback },
  { "ctd_ascii_upper", (void *)_cffi_f_ctd_ascii_upper, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 22), (void *)_cffi_d_ctd_ascii_upper },
  { "ctd_compute_stats_i32", (void *)_cffi_f_ctd_compute_stats_i32, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 83), (void *)_cffi_d_ctd_compute_stats_i32 },
  { "ctd_copy_bytes", (void *)_cffi_f_ctd_copy_bytes, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 105), (void *)_cffi_d_ctd_copy_bytes },
  { "ctd_copy_string", (void *)_cffi_f_ctd_copy_string, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 26), (void *)_cffi_d_ctd_copy_string },
  { "ctd_counter_add", (void *)_cffi_f_ctd_counter_add, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 32), (void *)_cffi_d_ctd_counter_add },
  { "ctd_counter_create", (void *)_cffi_f_ctd_counter_create, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 11), (void *)_cffi_d_ctd_counter_create },
  { "ctd_counter_destroy", (void *)_cffi_f_ctd_counter_destroy, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 154), (void *)_cffi_d_ctd_counter_destroy },
  { "ctd_counter_get", (void *)_cffi_f_ctd_counter_get, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 37), (void *)_cffi_d_ctd_counter_get },
  { "ctd_divide", (void *)_cffi_f_ctd_divide, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 55), (void *)_cffi_d_ctd_divide },
  { "ctd_free", (void *)_cffi_f_ctd_free, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 157), (void *)_cffi_d_ctd_free },
  { "ctd_get_binary_operation", (void *)_cffi_f_ctd_get_binary_operation, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 137), (void *)_cffi_d_ctd_get_binary_operation },
  { "ctd_get_magic", (void *)_cffi_f_ctd_get_magic, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 67), (void *)_cffi_d_ctd_get_magic },
  { "ctd_global_constant", (void *)_cffi_const_ctd_global_constant, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "ctd_global_counter", (void *)_cffi_var_ctd_global_counter, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 7), (void *)0 },
  { "ctd_global_counter_increment", (void *)_cffi_f_ctd_global_counter_increment, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 135), (void *)_cffi_d_ctd_global_counter_increment },
  { "ctd_global_counter_reset", (void *)_cffi_f_ctd_global_counter_reset, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 160), (void *)_cffi_d_ctd_global_counter_reset },
  { "ctd_global_name", (void *)_cffi_var_ctd_global_name, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 165), (void *)0 },
  { "ctd_global_origin", (void *)_cffi_const_ctd_global_origin, _CFFI_OP(_CFFI_OP_CONSTANT, 15), (void *)0 },
  { "ctd_hypot_squared", (void *)_cffi_f_ctd_hypot_squared, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 122), (void *)_cffi_d_ctd_hypot_squared },
  { "ctd_increment", (void *)_cffi_f_ctd_increment, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 67), (void *)_cffi_d_ctd_increment },
  { "ctd_make_sequence_i32", (void *)_cffi_f_ctd_make_sequence_i32, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 93), (void *)_cffi_d_ctd_make_sequence_i32 },
  { "ctd_negate_i32", (void *)_cffi_f_ctd_negate_i32, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 144), (void *)_cffi_d_ctd_negate_i32 },
  { "ctd_operation_add", (void *)_cffi_f_ctd_operation_add, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 126), (void *)_cffi_d_ctd_operation_add },
  { "ctd_operation_multiply", (void *)_cffi_f_ctd_operation_multiply, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 126), (void *)_cffi_d_ctd_operation_multiply },
  { "ctd_point_add", (void *)_cffi_f_ctd_point_add, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 14), (void *)_cffi_d_ctd_point_add },
  { "ctd_point_dot", (void *)_cffi_f_ctd_point_dot, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 118), (void *)_cffi_d_ctd_point_dot },
  { "ctd_point_make", (void *)_cffi_f_ctd_point_make, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 18), (void *)_cffi_d_ctd_point_make },
  { "ctd_point_translate", (void *)_cffi_f_ctd_point_translate, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 41), (void *)_cffi_d_ctd_point_translate },
  { "ctd_record_initialize", (void *)_cffi_f_ctd_record_initialize, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 46), (void *)_cffi_d_ctd_record_initialize },
  { "ctd_reverse_i32", (void *)_cffi_f_ctd_reverse_i32, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 74), (void *)_cffi_d_ctd_reverse_i32 },
  { "ctd_scale_i32", (void *)_cffi_f_ctd_scale_i32, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 78), (void *)_cffi_d_ctd_scale_i32 },
  { "ctd_select_static_string", (void *)_cffi_f_ctd_select_static_string, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 6), (void *)_cffi_d_ctd_select_static_string },
  { "ctd_status_name", (void *)_cffi_f_ctd_status_name, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 3), (void *)_cffi_d_ctd_status_name },
  { "ctd_string_length", (void *)_cffi_f_ctd_string_length, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 147), (void *)_cffi_d_ctd_string_length },
  { "ctd_subtract", (void *)_cffi_f_ctd_subtract, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 126), (void *)_cffi_d_ctd_subtract },
  { "ctd_sum_i32", (void *)_cffi_f_ctd_sum_i32, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 88), (void *)_cffi_d_ctd_sum_i32 },
  { "ctd_swap_i32", (void *)_cffi_f_ctd_swap_i32, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 70), (void *)_cffi_d_ctd_swap_i32 },
  { "ctd_value_as_f64", (void *)_cffi_f_ctd_value_as_f64, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 51), (void *)_cffi_d_ctd_value_as_f64 },
  { "ctd_value_from_f64", (void *)_cffi_f_ctd_value_from_f64, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 112), (void *)_cffi_d_ctd_value_from_f64 },
  { "ctd_value_from_i64", (void *)_cffi_f_ctd_value_from_i64, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 115), (void *)_cffi_d_ctd_value_from_i64 },
  { "ctd_version", (void *)_cffi_f_ctd_version, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 9), (void *)_cffi_d_ctd_version },
  { "ctd_xor_bytes", (void *)_cffi_f_ctd_xor_bytes, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 100), (void *)_cffi_d_ctd_xor_bytes },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "x", offsetof(ctd_point, x),
         sizeof(((ctd_point *)0)->x),
         _CFFI_OP(_CFFI_OP_NOOP, 19) },
  { "y", offsetof(ctd_point, y),
         sizeof(((ctd_point *)0)->y),
         _CFFI_OP(_CFFI_OP_NOOP, 19) },
  { "id", offsetof(ctd_record, id),
          sizeof(((ctd_record *)0)->id),
          _CFFI_OP(_CFFI_OP_NOOP, 48) },
  { "name", offsetof(ctd_record, name),
            sizeof(((ctd_record *)0)->name),
            _CFFI_OP(_CFFI_OP_NOOP, 163) },
  { "values", offsetof(ctd_record, values),
              sizeof(((ctd_record *)0)->values),
              _CFFI_OP(_CFFI_OP_NOOP, 172) },
  { "count", offsetof(ctd_stats, count),
             sizeof(((ctd_stats *)0)->count),
             _CFFI_OP(_CFFI_OP_NOOP, 24) },
  { "minimum", offsetof(ctd_stats, minimum),
               sizeof(((ctd_stats *)0)->minimum),
               _CFFI_OP(_CFFI_OP_NOOP, 48) },
  { "maximum", offsetof(ctd_stats, maximum),
               sizeof(((ctd_stats *)0)->maximum),
               _CFFI_OP(_CFFI_OP_NOOP, 48) },
  { "sum", offsetof(ctd_stats, sum),
           sizeof(((ctd_stats *)0)->sum),
           _CFFI_OP(_CFFI_OP_NOOP, 116) },
  { "mean", offsetof(ctd_stats, mean),
            sizeof(((ctd_stats *)0)->mean),
            _CFFI_OP(_CFFI_OP_NOOP, 19) },
  { "kind", offsetof(ctd_value, kind),
            sizeof(((ctd_value *)0)->kind),
            _CFFI_OP(_CFFI_OP_NOOP, 168) },
  { "number", offsetof(ctd_value, number),
              sizeof(((ctd_value *)0)->number),
              _CFFI_OP(_CFFI_OP_NOOP, 167) },
  { "i64", offsetof(ctd_number, i64),
           sizeof(((ctd_number *)0)->i64),
           _CFFI_OP(_CFFI_OP_NOOP, 116) },
  { "f64", offsetof(ctd_number, f64),
           sizeof(((ctd_number *)0)->f64),
           _CFFI_OP(_CFFI_OP_NOOP, 19) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "ctd_counter", 166, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "ctd_number", 167, _CFFI_F_UNION|_CFFI_F_CHECK_FIELDS,
    sizeof(ctd_number), offsetof(struct _cffi_align__ctd_number, y), 12, 2 },
  { "ctd_point", 15, _CFFI_F_CHECK_FIELDS,
    sizeof(ctd_point), offsetof(struct _cffi_align__ctd_point, y), 0, 2 },
  { "ctd_record", 169, _CFFI_F_CHECK_FIELDS,
    sizeof(ctd_record), offsetof(struct _cffi_align__ctd_record, y), 2, 3 },
  { "ctd_stats", 170, _CFFI_F_CHECK_FIELDS,
    sizeof(ctd_stats), offsetof(struct _cffi_align__ctd_stats, y), 5, 5 },
  { "ctd_value", 171, _CFFI_F_CHECK_FIELDS,
    sizeof(ctd_value), offsetof(struct _cffi_align__ctd_value, y), 10, 2 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "ctd_number_kind", 168, _cffi_prim_int(sizeof(ctd_number_kind), ((ctd_number_kind)-1) <= 0),
    "CTD_NUMBER_I64,CTD_NUMBER_F64" },
  { "ctd_status", 4, _cffi_prim_int(sizeof(ctd_status), ((ctd_status)-1) <= 0),
    "CTD_OK,CTD_ERROR_NULL,CTD_ERROR_RANGE,CTD_ERROR_CAPACITY,CTD_ERROR_ALLOCATION,CTD_ERROR_DIVIDE_BY_ZERO" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "ctd_binary_callback", 63 },
  { "ctd_binary_operation", 174 },
  { "ctd_counter", 166 },
  { "ctd_number", 167 },
  { "ctd_number_kind", 168 },
  { "ctd_point", 15 },
  { "ctd_record", 169 },
  { "ctd_stats", 170 },
  { "ctd_status", 4 },
  { "ctd_value", 171 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  55,  /* num_globals */
  6,  /* num_struct_unions */
  2,  /* num_enums */
  10,  /* num_typenames */
  NULL,  /* no includes */
  176,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit__ctd_wrapper(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
    return NULL;
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
     PyInit__ctd_wrapper(void) { return NULL; }
#  endif
#else
PyMODINIT_FUNC
PyInit__ctd_wrapper(void)
{
  return _cffi_init("_ctd_wrapper", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
